Minor devcontainer updates
cse-labs/ratify pull request #36
Opened 2022-10-14 21:51 UTC by cmaclaughlin

# Description

Added a readme and added apt-get install protobuf-compiler package to the Dockerfile.

In the future, additional notes will be needed outlining go packages required to generate go code specifically with protoc. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] Does the affected code have corresponding tests?
- [ ] Are the changes documented, not just with inline documentation, but also with conceptual documentation such as an overview of a new feature, or task-based documentation like a tutorial? Consider if this change should be announced on your project blog.
- [ ] Does this introduce breaking changes that would require an announcement or bumping the major version?
- [ ] Do all new files have appropriate license header?

2022-10-18 14:56 UTC, mluker approved these changes
lgtm

2022-10-18 22:15 UTC, Joll59 requested changes

2022-10-20 21:18 UTC, cmaclaughlin commented on experimental/ratify/proto/README.md
> +protoc --go_out=${PATH_TO_OUT} --go-grpc_out=${PATH_TO_OUT} ${PATH_TO_PROTO_FILE}
since this command will be updated with the next PR, going to mark as resolved.

2022-10-21 16:59 UTC, Joll59 approved these changes

2022-10-21 16:59 UTC, merged